### PR TITLE
making it look a little more like the famous node LTS schedule image

### PR DESCRIPTION
**Pull request by sirgallifrey**
output

There are much more improvements that can be made, if you like I can continue on this :)

### CODE REVIEW

**Comment by sirgallifrey** [comment]
Just noticed Node.js 10 is trimmed... Going to fix that right away

**Comment by cjihrig** [comment]
The image looks GREAT! Thank you. I'll review the code later.

**Comment by sirgallifrey** [comment]
Now there is a little more left margin and Node.js 10 wont overflow the image

output

**Comment by cjihrig** [comment]
Landed in c0fccb3997e2371e78c5069f2620cba7740f5080. Thanks!

**Pull request closed without merging**
