### PR TITLE
Add animations to bars ✨📊✨

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
Not production ready, probably needs a switch and be less shitty with multiple bars 👩‍🔬

(Never done svg stuff so more of test but if I can do some easy things to make this nice I'm totally open for it!)

### CODE REVIEW

**Comment by sirgallifrey** [comment]
novo projeto

showcasing

**Comment by cjihrig** [comment]
Put it behind a flag and I'm good with it :-)

**Comment by arb** [comment]
This looks awesome!

**Comment by AdriVanHoudt** [comment]
Added the flag 🎏

**Comment by cjihrig** [comment]
Landed in 5453d9bc1480d627306dfc1d751b6c042f7cc792. Thanks!

**Comment by AdriVanHoudt** [comment]
✨

**Pull request closed without merging**
